name: pokedex
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: 0.12.2
  rxdart: 0.24.1
  palette_generator: 0.2.3
  provider: 4.1.3
  kiwi: 2.0.0
  flutter_svg: 0.17.4
  meta: 1.1.8
  percent_indicator: 2.1.3
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
    - assets/
